export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: string
  image: string
  tags: string[]
  available: boolean
  popular?: boolean
  spicyLevel?: number
}

export const menuItems: MenuItem[] = [
  // Appetizers
  {
    id: "app-1",
    name: "Spring Rolls",
    description: "Crispy vegetable spring rolls served with sweet and sour dipping sauce. A perfect start to your meal.",
    price: 25,
    category: "appetizers",
    image: "/images/menu/spring-rolls.jpg",
    tags: ["Vegetarian"],
    available: true,
    popular: true,
  },
  {
    id: "app-2",
    name: "Chicken Wings",
    description: "Spicy buffalo wings marinated in our signature sauce, served with blue cheese dip and celery sticks.",
    price: 35,
    category: "appetizers",
    image: "/images/menu/chicken-wings.jpg",
    tags: ["Spicy"],
    available: true,
    popular: true,
    spicyLevel: 3,
  },
  {
    id: "app-3",
    name: "Calamari",
    description: "Crispy fried calamari rings with lemon aioli. Tender and perfectly seasoned seafood delight.",
    price: 40,
    category: "appetizers",
    image: "/images/menu/calamari.jpg",
    tags: [],
    available: true,
  },
  {
    id: "app-4",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, garlic, and mozzarella. Classic Italian starter.",
    price: 30,
    category: "appetizers",
    image: "/images/menu/bruschetta.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "app-5",
    name: "Shrimp Cocktail",
    description: "Fresh jumbo shrimp served with tangy cocktail sauce and lemon wedges.",
    price: 45,
    category: "appetizers",
    image: "/images/menu/shrimp-cocktail.jpg",
    tags: [],
    available: true,
  },

  // Main Course
  {
    id: "main-1",
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon grilled to perfection with lemon butter sauce, served with seasonal vegetables and rice pilaf.",
    price: 85,
    category: "main-course",
    image: "/images/menu/grilled-salmon.jpg",
    tags: ["Gluten-free"],
    available: true,
    popular: true,
  },
  {
    id: "main-2",
    name: "Beef Steak",
    description: "Tender 10oz ribeye steak cooked to your preference, served with mashed potatoes and grilled asparagus.",
    price: 95,
    category: "main-course",
    image: "/images/menu/beef-steak.jpg",
    tags: [],
    available: true,
    popular: true,
  },
  {
    id: "main-3",
    name: "Chicken Alfredo Pasta",
    description: "Creamy alfredo pasta with grilled chicken breast, parmesan cheese, and fresh herbs.",
    price: 70,
    category: "main-course",
    image: "/images/menu/chicken-alfredo.jpg",
    tags: [],
    available: true,
  },
  {
    id: "main-4",
    name: "Jollof Rice Special",
    description: "Authentic Ghanaian jollof rice with tender chicken, plantains, and spicy tomato sauce.",
    price: 65,
    category: "main-course",
    image: "/images/menu/jollof-rice.jpg",
    tags: ["Spicy"],
    available: true,
    popular: true,
    spicyLevel: 2,
  },
  {
    id: "main-5",
    name: "Grilled Chicken Breast",
    description: "Marinated chicken breast grilled to perfection, served with roasted vegetables and quinoa.",
    price: 75,
    category: "main-course",
    image: "/images/menu/grilled-chicken.jpg",
    tags: ["Gluten-free"],
    available: true,
  },
  {
    id: "main-6",
    name: "Vegetarian Risotto",
    description: "Creamy arborio rice with seasonal vegetables, parmesan cheese, and fresh herbs.",
    price: 60,
    category: "main-course",
    image: "/images/menu/risotto.jpg",
    tags: ["Vegetarian"],
    available: true,
  },

  // Grill
  {
    id: "grill-1",
    name: "Mixed Grill Platter",
    description: "A generous platter featuring grilled chicken, beef, lamb, and sausages with sides of rice, plantain, and salad.",
    price: 120,
    category: "grill",
    image: "/images/menu/mixed-grill.jpg",
    tags: [],
    available: true,
    popular: true,
  },
  {
    id: "grill-2",
    name: "BBQ Ribs",
    description: "Slow-cooked pork ribs glazed with our signature BBQ sauce, served with coleslaw and fries.",
    price: 90,
    category: "grill",
    image: "/images/menu/bbq-ribs.jpg",
    tags: [],
    available: true,
    popular: true,
  },
  {
    id: "grill-3",
    name: "Lamb Chops",
    description: "Tender lamb chops marinated in herbs and spices, grilled to perfection with mint sauce.",
    price: 100,
    category: "grill",
    image: "/images/menu/lamb-chops.jpg",
    tags: [],
    available: true,
  },
  {
    id: "grill-4",
    name: "Grilled Fish",
    description: "Whole tilapia grilled with spices, served with banku and pepper sauce.",
    price: 80,
    category: "grill",
    image: "/images/menu/grilled-fish.jpg",
    tags: ["Gluten-free"],
    available: true,
  },
  {
    id: "grill-5",
    name: "Beef Kebab",
    description: "Marinated beef skewers grilled over charcoal, served with rice and salad.",
    price: 75,
    category: "grill",
    image: "/images/menu/beef-kebab.jpg",
    tags: ["Spicy"],
    available: true,
    spicyLevel: 2,
  },

  // Sides
  {
    id: "side-1",
    name: "Jollof Rice",
    description: "Classic Ghanaian jollof rice, perfectly spiced and flavorful.",
    price: 20,
    category: "sides",
    image: "/images/menu/jollof-rice-side.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "side-2",
    name: "French Fries",
    description: "Crispy golden fries served with ketchup and mayonnaise.",
    price: 15,
    category: "sides",
    image: "/images/menu/french-fries.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "side-3",
    name: "Grilled Vegetables",
    description: "Seasonal vegetables grilled to perfection with olive oil and herbs.",
    price: 25,
    category: "sides",
    image: "/images/menu/grilled-vegetables.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },
  {
    id: "side-4",
    name: "Coleslaw",
    description: "Fresh cabbage and carrot salad with creamy dressing.",
    price: 18,
    category: "sides",
    image: "/images/menu/coleslaw.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "side-5",
    name: "Plantain",
    description: "Sweet fried plantain, a perfect complement to any meal.",
    price: 22,
    category: "sides",
    image: "/images/menu/plantain.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },

  // Desserts
  {
    id: "dessert-1",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten center, served with vanilla ice cream and fresh berries.",
    price: 30,
    category: "desserts",
    image: "/images/menu/chocolate-lava.jpg",
    tags: ["Vegetarian"],
    available: true,
    popular: true,
  },
  {
    id: "dessert-2",
    name: "Tiramisu",
    description: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    price: 35,
    category: "desserts",
    image: "/images/menu/tiramisu.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "dessert-3",
    name: "Ice Cream Selection",
    description: "Three scoops of premium ice cream in your choice of flavors: vanilla, chocolate, or strawberry.",
    price: 25,
    category: "desserts",
    image: "/images/menu/ice-cream.jpg",
    tags: ["Vegetarian"],
    available: true,
  },
  {
    id: "dessert-4",
    name: "Fruit Salad",
    description: "Fresh seasonal fruits with a drizzle of honey and mint.",
    price: 20,
    category: "desserts",
    image: "/images/menu/fruit-salad.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },

  // Beverages
  {
    id: "bev-1",
    name: "Fresh Juices",
    description: "Freshly squeezed orange, mango, or pineapple juice. Served chilled.",
    price: 15,
    category: "beverages",
    image: "/images/menu/fresh-juice.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },
  {
    id: "bev-2",
    name: "Soft Drinks",
    description: "Selection of carbonated soft drinks: Coca-Cola, Sprite, Fanta, or Pepsi.",
    price: 10,
    category: "beverages",
    image: "/images/menu/soft-drinks.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },
  {
    id: "bev-3",
    name: "Specialty Cocktails",
    description: "Handcrafted cocktails made with premium spirits. Ask your server for today's specials.",
    price: 35,
    category: "beverages",
    image: "/images/menu/cocktails.jpg",
    tags: [],
    available: true,
  },
  {
    id: "bev-4",
    name: "Coffee & Tea",
    description: "Freshly brewed coffee or selection of premium teas. Served hot or iced.",
    price: 12,
    category: "beverages",
    image: "/images/menu/coffee-tea.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },
  {
    id: "bev-5",
    name: "Smoothies",
    description: "Blended fruit smoothies: strawberry, banana, or mixed berry. Made with fresh fruits.",
    price: 18,
    category: "beverages",
    image: "/images/menu/smoothies.jpg",
    tags: ["Vegetarian", "Vegan", "Gluten-free"],
    available: true,
  },

  // Specials
  {
    id: "spec-1",
    name: "Chef's Special Platter",
    description: "A curated selection of our chef's favorite dishes. Changes daily. Ask your server for details.",
    price: 110,
    category: "specials",
    image: "/images/menu/chef-special.jpg",
    tags: [],
    available: true,
    popular: true,
  },
  {
    id: "spec-2",
    name: "Weekend Special: Seafood Platter",
    description: "Fresh catch of the day with grilled prawns, calamari, and fish. Available weekends only.",
    price: 95,
    category: "specials",
    image: "/images/menu/seafood-platter.jpg",
    tags: ["Gluten-free"],
    available: true,
  },
  {
    id: "spec-3",
    name: "Family Combo",
    description: "Perfect for sharing! Includes mixed grill, jollof rice, plantain, and salad. Serves 4-5 people.",
    price: 180,
    category: "specials",
    image: "/images/menu/family-combo.jpg",
    tags: [],
    available: true,
    popular: true,
  },
]

export const categories = [
  { value: "all", label: "All" },
  { value: "appetizers", label: "Appetizers" },
  { value: "main-course", label: "Main Course" },
  { value: "grill", label: "Grill" },
  { value: "sides", label: "Sides" },
  { value: "desserts", label: "Desserts" },
  { value: "beverages", label: "Beverages" },
  { value: "specials", label: "Specials" },
] as const

export type SortOption = "default" | "price-low" | "price-high" | "popular" | "new"



